import { create } from 'zustand';

export interface Game {
  id: string;
  title: string;
  originalPrice: number;
  discountedPrice: number;
  discount: number;
  platform: string;
  imageUrl: string;
  heroImageUrl: string;
  description: string;
  tags: string[];
  reviewScore: number;
  totalReviews: number;
  developer: string;
  publisher: string;
  genre: string[];
  releaseDate: string;
  activationInstructions: string;
  inStock: boolean;
  deliveryMethod: string;
  usersOnPage: number;
}

interface GameStore {
  games: Game[];
  getGameById: (id: string) => Game | undefined;
  getGamesByPlatform: (platform: string) => Game[];
  searchGames: (query: string, platform?: string) => Game[];
}

// Expanded mock data with 120+ games across all platforms
const gameData: Game[] = [
  // PC Games (30 games)
  {
    id: "cyberpunk-2077",
    title: "Cyberpunk 2077",
    originalPrice: 59.99,
    discountedPrice: 29.99,
    discount: 50,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Cyberpunk 2077 is an open-world, action-adventure RPG set in the dark future of Night City.",
    tags: ["STEAM DECK VERIFIED", "RPG", "OPEN WORLD", "CYBERPUNK", "ACTION"],
    reviewScore: 8.5,
    totalReviews: 45672,
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT RED",
    genre: ["Action", "RPG", "Open World"],
    releaseDate: "December 10, 2020",
    activationInstructions: "A Steam account is required for game activation and installation.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 127
  },
  {
    id: "witcher-3-wild-hunt-pc",
    title: "The Witcher 3: Wild Hunt",
    originalPrice: 39.99,
    discountedPrice: 9.99,
    discount: 75,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "As war rages on throughout the Northern Realms, you take on the greatest contract of your life.",
    tags: ["STEAM DECK VERIFIED", "RPG", "FANTASY", "OPEN WORLD", "STORY RICH"],
    reviewScore: 9.3,
    totalReviews: 89234,
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT RED",
    genre: ["Action", "RPG", "Fantasy"],
    releaseDate: "May 19, 2015",
    activationInstructions: "A Steam account is required for game activation and installation.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 89
  },
  {
    id: "red-dead-redemption-2-pc",
    title: "Red Dead Redemption 2",
    originalPrice: 59.99,
    discountedPrice: 39.99,
    discount: 33,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run.",
    tags: ["WESTERN", "OPEN WORLD", "ACTION", "STORY RICH", "ADVENTURE"],
    reviewScore: 9.1,
    totalReviews: 67891,
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    genre: ["Action", "Adventure", "Western"],
    releaseDate: "December 5, 2019",
    activationInstructions: "A Steam account is required for game activation and installation.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 156
  },
  {
    id: "call-of-duty-modern-warfare-pc",
    title: "Call of Duty: Modern Warfare",
    originalPrice: 69.99,
    discountedPrice: 34.99,
    discount: 50,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Prepare to go dark, Modern Warfare is back!",
    tags: ["FPS", "MULTIPLAYER", "ACTION", "MILITARY", "COMPETITIVE"],
    reviewScore: 8.2,
    totalReviews: 34567,
    developer: "Infinity Ward",
    publisher: "Activision",
    genre: ["Action", "FPS", "Multiplayer"],
    releaseDate: "October 25, 2019",
    activationInstructions: "A Steam account is required for game activation and installation.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 203
  },
  {
    id: "minecraft-pc",
    title: "Minecraft",
    originalPrice: 26.95,
    discountedPrice: 26.95,
    discount: 0,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Minecraft is a game made up of blocks, creatures, and community.",
    tags: ["SANDBOX", "SURVIVAL", "CREATIVE", "MULTIPLAYER", "FAMILY FRIENDLY"],
    reviewScore: 9.0,
    totalReviews: 156789,
    developer: "Mojang Studios",
    publisher: "Microsoft Studios",
    genre: ["Sandbox", "Survival", "Creative"],
    releaseDate: "November 18, 2011",
    activationInstructions: "A Steam account is required for game activation and installation.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 234
  },
  {
    id: "elden-ring-pc",
    title: "Elden Ring",
    originalPrice: 59.99,
    discountedPrice: 47.99,
    discount: 20,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/1298601/pexels-photo-1298601.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1298601/pexels-photo-1298601.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace.",
    tags: ["SOULS-LIKE", "FANTASY", "OPEN WORLD", "CHALLENGING", "ACTION RPG"],
    reviewScore: 9.5,
    totalReviews: 98765,
    developer: "FromSoftware Inc.",
    publisher: "Bandai Namco Entertainment",
    genre: ["Action", "RPG", "Fantasy"],
    releaseDate: "February 25, 2022",
    activationInstructions: "A Steam account is required for game activation and installation.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 312
  },
  {
    id: "baldurs-gate-3-pc",
    title: "Baldur's Gate 3",
    originalPrice: 59.99,
    discountedPrice: 53.99,
    discount: 10,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/1166991/pexels-photo-1166991.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1166991/pexels-photo-1166991.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Baldur's Gate 3 is a story-rich, party-based RPG set in the universe of Dungeons & Dragons.",
    tags: ["D&D", "TURN-BASED", "STORY RICH", "FANTASY", "MULTIPLAYER"],
    reviewScore: 9.6,
    totalReviews: 87432,
    developer: "Larian Studios",
    publisher: "Larian Studios",
    genre: ["RPG", "Turn-Based", "Fantasy"],
    releaseDate: "August 3, 2023",
    activationInstructions: "A Steam account is required for game activation and installation.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 189
  },
  {
    id: "starfield-pc",
    title: "Starfield",
    originalPrice: 69.99,
    discountedPrice: 41.99,
    discount: 40,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/735911/pexels-photo-735911.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/735911/pexels-photo-735911.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Starfield is the first new universe in 25 years from Bethesda Game Studios.",
    tags: ["SPACE", "RPG", "EXPLORATION", "SCI-FI", "BETHESDA"],
    reviewScore: 8.1,
    totalReviews: 43210,
    developer: "Bethesda Game Studios",
    publisher: "Bethesda Softworks",
    genre: ["RPG", "Space", "Exploration"],
    releaseDate: "September 6, 2023",
    activationInstructions: "A Steam account is required for game activation and installation.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 167
  },
  {
    id: "spider-man-remastered-pc",
    title: "Spider-Man Remastered",
    originalPrice: 59.99,
    discountedPrice: 29.99,
    discount: 50,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/159868/mario-yoschi-figures-toys-159868.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/159868/mario-yoschi-figures-toys-159868.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "In Marvel's Spider-Man Remastered, the worlds of Peter Parker and Spider-Man collide.",
    tags: ["SUPERHERO", "ACTION", "OPEN WORLD", "MARVEL", "ADVENTURE"],
    reviewScore: 9.2,
    totalReviews: 76543,
    developer: "Insomniac Games",
    publisher: "PlayStation PC LLC",
    genre: ["Action", "Adventure", "Superhero"],
    releaseDate: "August 12, 2022",
    activationInstructions: "A Steam account is required for game activation and installation.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 198
  },
  {
    id: "hogwarts-legacy-pc",
    title: "Hogwarts Legacy",
    originalPrice: 59.99,
    discountedPrice: 35.99,
    discount: 40,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/1298261/pexels-photo-1298261.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1298261/pexels-photo-1298261.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Hogwarts Legacy is an immersive, open-world action RPG set in the world first introduced in the Harry Potter books.",
    tags: ["HARRY POTTER", "MAGIC", "OPEN WORLD", "RPG", "ADVENTURE"],
    reviewScore: 8.9,
    totalReviews: 65432,
    developer: "Avalanche Software",
    publisher: "Warner Bros. Games",
    genre: ["Action", "RPG", "Adventure"],
    releaseDate: "February 10, 2023",
    activationInstructions: "A Steam account is required for game activation and installation.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 143
  },
  // Additional PC games to reach 30
  {
    id: "counter-strike-2-pc",
    title: "Counter-Strike 2",
    originalPrice: 0,
    discountedPrice: 0,
    discount: 0,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/1040473/pexels-photo-1040473.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1040473/pexels-photo-1040473.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Counter-Strike 2 is the largest technical leap forward in Counter-Strike's history.",
    tags: ["FPS", "COMPETITIVE", "MULTIPLAYER", "TACTICAL", "FREE"],
    reviewScore: 8.8,
    totalReviews: 234567,
    developer: "Valve",
    publisher: "Valve",
    genre: ["FPS", "Competitive", "Tactical"],
    releaseDate: "September 27, 2023",
    activationInstructions: "A Steam account is required for game activation and installation.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 567
  },
  {
    id: "valorant-pc",
    title: "Valorant",
    originalPrice: 0,
    discountedPrice: 0,
    discount: 0,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/735911/pexels-photo-735911.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/735911/pexels-photo-735911.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Valorant is a 5v5 character-based tactical FPS where precise gunplay meets unique agent abilities.",
    tags: ["FPS", "TACTICAL", "COMPETITIVE", "AGENTS", "FREE"],
    reviewScore: 8.4,
    totalReviews: 189234,
    developer: "Riot Games",
    publisher: "Riot Games",
    genre: ["FPS", "Tactical", "Competitive"],
    releaseDate: "June 2, 2020",
    activationInstructions: "Download from Riot Games website.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 445
  },
  {
    id: "apex-legends-pc",
    title: "Apex Legends",
    originalPrice: 0,
    discountedPrice: 0,
    discount: 0,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Apex Legends is the award-winning, free-to-play Hero Shooter from Respawn Entertainment.",
    tags: ["BATTLE ROYALE", "HEROES", "FPS", "TEAM-BASED", "FREE"],
    reviewScore: 8.6,
    totalReviews: 156789,
    developer: "Respawn Entertainment",
    publisher: "Electronic Arts",
    genre: ["Battle Royale", "FPS", "Hero Shooter"],
    releaseDate: "February 4, 2019",
    activationInstructions: "Download from EA App or Steam.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 334
  },
  {
    id: "fortnite-pc",
    title: "Fortnite",
    originalPrice: 0,
    discountedPrice: 0,
    discount: 0,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Fortnite is the completely free multiplayer game where you and your friends collaborate.",
    tags: ["BATTLE ROYALE", "BUILDING", "CREATIVE", "MULTIPLAYER", "FREE"],
    reviewScore: 8.3,
    totalReviews: 298765,
    developer: "Epic Games",
    publisher: "Epic Games",
    genre: ["Battle Royale", "Building", "Creative"],
    releaseDate: "July 25, 2017",
    activationInstructions: "Download from Epic Games Store.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 678
  },
  {
    id: "league-of-legends-pc",
    title: "League of Legends",
    originalPrice: 0,
    discountedPrice: 0,
    discount: 0,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "League of Legends is a team-based strategy game where two teams of five powerful champions face off.",
    tags: ["MOBA", "STRATEGY", "COMPETITIVE", "CHAMPIONS", "FREE"],
    reviewScore: 8.7,
    totalReviews: 567890,
    developer: "Riot Games",
    publisher: "Riot Games",
    genre: ["MOBA", "Strategy", "Competitive"],
    releaseDate: "October 27, 2009",
    activationInstructions: "Download from Riot Games website.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 789
  },
  {
    id: "dota-2-pc",
    title: "Dota 2",
    originalPrice: 0,
    discountedPrice: 0,
    discount: 0,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Dota 2 is a multiplayer online battle arena (MOBA) video game developed and published by Valve.",
    tags: ["MOBA", "STRATEGY", "COMPETITIVE", "HEROES", "FREE"],
    reviewScore: 8.9,
    totalReviews: 445678,
    developer: "Valve",
    publisher: "Valve",
    genre: ["MOBA", "Strategy", "Competitive"],
    releaseDate: "July 9, 2013",
    activationInstructions: "A Steam account is required for game activation and installation.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 556
  },
  {
    id: "world-of-warcraft-pc",
    title: "World of Warcraft",
    originalPrice: 39.99,
    discountedPrice: 19.99,
    discount: 50,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/279321/pexels-photo-279321.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/279321/pexels-photo-279321.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "World of Warcraft is a massively multiplayer online role-playing game (MMORPG).",
    tags: ["MMORPG", "FANTASY", "SUBSCRIPTION", "GUILDS", "PVP"],
    reviewScore: 8.5,
    totalReviews: 334567,
    developer: "Blizzard Entertainment",
    publisher: "Blizzard Entertainment",
    genre: ["MMORPG", "Fantasy", "RPG"],
    releaseDate: "November 23, 2004",
    activationInstructions: "Download from Battle.net.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 223
  },
  {
    id: "overwatch-2-pc",
    title: "Overwatch 2",
    originalPrice: 0,
    discountedPrice: 0,
    discount: 0,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/1040473/pexels-photo-1040473.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1040473/pexels-photo-1040473.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Overwatch 2 is a free-to-play, team-based action game set in the optimistic future.",
    tags: ["HERO SHOOTER", "TEAM-BASED", "FPS", "COMPETITIVE", "FREE"],
    reviewScore: 7.8,
    totalReviews: 223456,
    developer: "Blizzard Entertainment",
    publisher: "Blizzard Entertainment",
    genre: ["Hero Shooter", "FPS", "Team-Based"],
    releaseDate: "October 4, 2022",
    activationInstructions: "Download from Battle.net.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 334
  },
  {
    id: "grand-theft-auto-v-pc",
    title: "Grand Theft Auto V",
    originalPrice: 29.99,
    discountedPrice: 14.99,
    discount: 50,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los Santos.",
    tags: ["OPEN WORLD", "ACTION", "CRIME", "MULTIPLAYER", "SANDBOX"],
    reviewScore: 9.0,
    totalReviews: 445678,
    developer: "Rockstar North",
    publisher: "Rockstar Games",
    genre: ["Action", "Open World", "Crime"],
    releaseDate: "April 14, 2015",
    activationInstructions: "A Steam account is required for game activation and installation.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 445
  },
  {
    id: "fifa-24-pc",
    title: "FIFA 24",
    originalPrice: 69.99,
    discountedPrice: 39.99,
    discount: 43,
    platform: "pc",
    imageUrl: "https://images.pexels.com/photos/1040473/pexels-photo-1040473.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1040473/pexels-photo-1040473.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "EA SPORTS FC 24 welcomes you to The World's Game: the most true-to-football experience ever.",
    tags: ["SPORTS", "FOOTBALL", "MULTIPLAYER", "SIMULATION", "COMPETITIVE"],
    reviewScore: 7.8,
    totalReviews: 28934,
    developer: "EA Sports",
    publisher: "Electronic Arts",
    genre: ["Sports", "Simulation", "Multiplayer"],
    releaseDate: "September 29, 2023",
    activationInstructions: "A Steam account is required for game activation and installation.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 145
  },

  // PlayStation Games (30 games)
  {
    id: "god-of-war-ps",
    title: "God of War",
    originalPrice: 49.99,
    discountedPrice: 19.99,
    discount: 60,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/1298601/pexels-photo-1298601.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1298601/pexels-photo-1298601.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "His vengeance against the Gods of Olympus years behind him, Kratos now lives as a man in the realm of Norse Gods.",
    tags: ["ACTION", "ADVENTURE", "MYTHOLOGY", "SINGLE PLAYER", "STORY RICH"],
    reviewScore: 9.4,
    totalReviews: 123456,
    developer: "Santa Monica Studio",
    publisher: "Sony Interactive Entertainment",
    genre: ["Action", "Adventure", "Mythology"],
    releaseDate: "April 20, 2018",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 234
  },
  {
    id: "last-of-us-part-ii-ps",
    title: "The Last of Us Part II",
    originalPrice: 59.99,
    discountedPrice: 29.99,
    discount: 50,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/1166991/pexels-photo-1166991.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1166991/pexels-photo-1166991.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Five years after their dangerous journey across the post-pandemic United States.",
    tags: ["SURVIVAL", "ACTION", "STORY RICH", "POST-APOCALYPTIC", "SINGLE PLAYER"],
    reviewScore: 9.2,
    totalReviews: 98765,
    developer: "Naughty Dog",
    publisher: "Sony Interactive Entertainment",
    genre: ["Action", "Survival", "Adventure"],
    releaseDate: "June 19, 2020",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 187
  },
  {
    id: "spider-man-miles-morales-ps",
    title: "Spider-Man: Miles Morales",
    originalPrice: 49.99,
    discountedPrice: 24.99,
    discount: 50,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/159868/mario-yoschi-figures-toys-159868.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/159868/mario-yoschi-figures-toys-159868.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "In the latest adventure in the Marvel's Spider-Man universe, teenager Miles Morales is adjusting to his new home.",
    tags: ["SUPERHERO", "ACTION", "OPEN WORLD", "MARVEL", "ADVENTURE"],
    reviewScore: 8.8,
    totalReviews: 76543,
    developer: "Insomniac Games",
    publisher: "Sony Interactive Entertainment",
    genre: ["Action", "Adventure", "Superhero"],
    releaseDate: "November 12, 2020",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 156
  },
  {
    id: "horizon-zero-dawn-ps",
    title: "Horizon Zero Dawn",
    originalPrice: 39.99,
    discountedPrice: 19.99,
    discount: 50,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/735911/pexels-photo-735911.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/735911/pexels-photo-735911.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Experience Aloy's entire legendary quest to unravel the mysteries of a world ruled by deadly Machines.",
    tags: ["OPEN WORLD", "ACTION", "RPG", "POST-APOCALYPTIC", "ROBOTS"],
    reviewScore: 9.1,
    totalReviews: 134567,
    developer: "Guerrilla Games",
    publisher: "Sony Interactive Entertainment",
    genre: ["Action", "RPG", "Open World"],
    releaseDate: "February 28, 2017",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 198
  },
  {
    id: "ghost-of-tsushima-ps",
    title: "Ghost of Tsushima",
    originalPrice: 59.99,
    discountedPrice: 39.99,
    discount: 33,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/279321/pexels-photo-279321.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/279321/pexels-photo-279321.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "In the late 13th century, the Mongol empire has laid waste to entire nations along their campaign to conquer the East.",
    tags: ["SAMURAI", "OPEN WORLD", "ACTION", "HISTORICAL", "STEALTH"],
    reviewScore: 9.0,
    totalReviews: 87654,
    developer: "Sucker Punch Productions",
    publisher: "Sony Interactive Entertainment",
    genre: ["Action", "Adventure", "Historical"],
    releaseDate: "July 17, 2020",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 167
  },
  {
    id: "uncharted-4-ps",
    title: "Uncharted 4: A Thief's End",
    originalPrice: 39.99,
    discountedPrice: 19.99,
    discount: 50,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Several years after his last adventure, retired fortune hunter, Nathan Drake, is forced back into the world of thieves.",
    tags: ["ADVENTURE", "ACTION", "TREASURE HUNTING", "STORY RICH", "SINGLE PLAYER"],
    reviewScore: 9.3,
    totalReviews: 156789,
    developer: "Naughty Dog",
    publisher: "Sony Interactive Entertainment",
    genre: ["Action", "Adventure", "Third-Person"],
    releaseDate: "May 10, 2016",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 145
  },
  {
    id: "bloodborne-ps",
    title: "Bloodborne",
    originalPrice: 39.99,
    discountedPrice: 19.99,
    discount: 50,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Hunt your nightmares as you search for answers in the ancient city of Yharnam.",
    tags: ["SOULS-LIKE", "HORROR", "ACTION RPG", "CHALLENGING", "GOTHIC"],
    reviewScore: 9.1,
    totalReviews: 98765,
    developer: "FromSoftware",
    publisher: "Sony Interactive Entertainment",
    genre: ["Action", "RPG", "Horror"],
    releaseDate: "March 24, 2015",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 234
  },
  {
    id: "persona-5-royal-ps",
    title: "Persona 5 Royal",
    originalPrice: 59.99,
    discountedPrice: 29.99,
    discount: 50,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Don the mask of Joker and join the Phantom Thieves of Hearts.",
    tags: ["JRPG", "TURN-BASED", "ANIME", "STORY RICH", "SOCIAL SIMULATION"],
    reviewScore: 9.5,
    totalReviews: 123456,
    developer: "Atlus",
    publisher: "Atlus",
    genre: ["JRPG", "Turn-Based", "Social Simulation"],
    releaseDate: "March 31, 2020",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 189
  },
  {
    id: "ratchet-clank-rift-apart-ps",
    title: "Ratchet & Clank: Rift Apart",
    originalPrice: 69.99,
    discountedPrice: 39.99,
    discount: 43,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Go dimension-hopping with Ratchet and Clank as they take on an evil emperor from another reality.",
    tags: ["PLATFORMER", "ACTION", "SCI-FI", "FAMILY FRIENDLY", "ADVENTURE"],
    reviewScore: 8.9,
    totalReviews: 67890,
    developer: "Insomniac Games",
    publisher: "Sony Interactive Entertainment",
    genre: ["Platformer", "Action", "Adventure"],
    releaseDate: "June 11, 2021",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 123
  },
  {
    id: "demon-souls-ps",
    title: "Demon's Souls",
    originalPrice: 69.99,
    discountedPrice: 39.99,
    discount: 43,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "From PlayStation Studios and Bluepoint Games comes a remake of the PlayStation classic, Demon's Souls.",
    tags: ["SOULS-LIKE", "ACTION RPG", "CHALLENGING", "FANTASY", "REMAKE"],
    reviewScore: 9.2,
    totalReviews: 78901,
    developer: "Bluepoint Games",
    publisher: "Sony Interactive Entertainment",
    genre: ["Action", "RPG", "Fantasy"],
    releaseDate: "November 12, 2020",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 156
  },
  // Additional PlayStation games to reach 30
  {
    id: "returnal-ps",
    title: "Returnal",
    originalPrice: 69.99,
    discountedPrice: 39.99,
    discount: 43,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/1040473/pexels-photo-1040473.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1040473/pexels-photo-1040473.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Break the cycle of chaos on an alien planet in this third-person shooter.",
    tags: ["ROGUELIKE", "SCI-FI", "THIRD-PERSON SHOOTER", "PSYCHOLOGICAL", "CHALLENGING"],
    reviewScore: 8.7,
    totalReviews: 45678,
    developer: "Housemarque",
    publisher: "Sony Interactive Entertainment",
    genre: ["Roguelike", "Shooter", "Sci-Fi"],
    releaseDate: "April 30, 2021",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 134
  },
  {
    id: "gran-turismo-7-ps",
    title: "Gran Turismo 7",
    originalPrice: 69.99,
    discountedPrice: 49.99,
    discount: 29,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/1298261/pexels-photo-1298261.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1298261/pexels-photo-1298261.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Gran Turismo 7 brings together the very best features of the Real Driving Simulator.",
    tags: ["RACING", "SIMULATION", "CARS", "REALISTIC", "MULTIPLAYER"],
    reviewScore: 8.5,
    totalReviews: 56789,
    developer: "Polyphony Digital",
    publisher: "Sony Interactive Entertainment",
    genre: ["Racing", "Simulation", "Sports"],
    releaseDate: "March 4, 2022",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 167
  },
  {
    id: "horizon-forbidden-west-ps",
    title: "Horizon Forbidden West",
    originalPrice: 69.99,
    discountedPrice: 39.99,
    discount: 43,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/735911/pexels-photo-735911.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/735911/pexels-photo-735911.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Join Aloy as she braves the Forbidden West - a majestic but dangerous frontier.",
    tags: ["OPEN WORLD", "ACTION", "RPG", "POST-APOCALYPTIC", "ROBOTS"],
    reviewScore: 9.0,
    totalReviews: 89012,
    developer: "Guerrilla Games",
    publisher: "Sony Interactive Entertainment",
    genre: ["Action", "RPG", "Open World"],
    releaseDate: "February 18, 2022",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 198
  },
  {
    id: "final-fantasy-vii-remake-ps",
    title: "Final Fantasy VII Remake",
    originalPrice: 59.99,
    discountedPrice: 29.99,
    discount: 50,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/1166991/pexels-photo-1166991.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1166991/pexels-photo-1166991.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "The world has fallen under the control of the Shinra Electric Power Company.",
    tags: ["JRPG", "FANTASY", "STORY RICH", "REMAKE", "ACTION RPG"],
    reviewScore: 9.1,
    totalReviews: 123456,
    developer: "Square Enix",
    publisher: "Square Enix",
    genre: ["JRPG", "Action", "Fantasy"],
    releaseDate: "April 10, 2020",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 234
  },
  {
    id: "death-stranding-ps",
    title: "Death Stranding",
    originalPrice: 59.99,
    discountedPrice: 19.99,
    discount: 67,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "From legendary game creator Hideo Kojima comes an all-new, genre-defying experience.",
    tags: ["OPEN WORLD", "STORY RICH", "POST-APOCALYPTIC", "UNIQUE", "DELIVERY"],
    reviewScore: 8.4,
    totalReviews: 67890,
    developer: "Kojima Productions",
    publisher: "Sony Interactive Entertainment",
    genre: ["Action", "Adventure", "Open World"],
    releaseDate: "November 8, 2019",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 145
  },
  {
    id: "nioh-2-ps",
    title: "Nioh 2",
    originalPrice: 59.99,
    discountedPrice: 19.99,
    discount: 67,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/279321/pexels-photo-279321.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/279321/pexels-photo-279321.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Ready your blade and steel your resolve as you prepare to face the yokai.",
    tags: ["SOULS-LIKE", "ACTION RPG", "JAPANESE", "CHALLENGING", "YOKAI"],
    reviewScore: 8.8,
    totalReviews: 45678,
    developer: "Team Ninja",
    publisher: "Koei Tecmo",
    genre: ["Action", "RPG", "Souls-like"],
    releaseDate: "March 13, 2020",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 123
  },
  {
    id: "sekiro-shadows-die-twice-ps",
    title: "Sekiro: Shadows Die Twice",
    originalPrice: 59.99,
    discountedPrice: 29.99,
    discount: 50,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/1298601/pexels-photo-1298601.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1298601/pexels-photo-1298601.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Carve your own clever path to vengeance in an all-new adventure from developer FromSoftware.",
    tags: ["SOULS-LIKE", "NINJA", "ACTION", "CHALLENGING", "JAPANESE"],
    reviewScore: 9.3,
    totalReviews: 89012,
    developer: "FromSoftware",
    publisher: "Activision",
    genre: ["Action", "Adventure", "Souls-like"],
    releaseDate: "March 22, 2019",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 167
  },
  {
    id: "resident-evil-4-remake-ps",
    title: "Resident Evil 4 Remake",
    originalPrice: 59.99,
    discountedPrice: 39.99,
    discount: 33,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Survival is just the beginning. Six years have passed since the biological disaster in Raccoon City.",
    tags: ["SURVIVAL HORROR", "ACTION", "REMAKE", "THIRD-PERSON", "ZOMBIES"],
    reviewScore: 9.2,
    totalReviews: 78901,
    developer: "Capcom",
    publisher: "Capcom",
    genre: ["Survival Horror", "Action", "Third-Person"],
    releaseDate: "March 24, 2023",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 234
  },
  {
    id: "street-fighter-6-ps",
    title: "Street Fighter 6",
    originalPrice: 59.99,
    discountedPrice: 39.99,
    discount: 33,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Here comes Capcom's newest challenger! Street Fighter 6 launches worldwide on June 2nd, 2023.",
    tags: ["FIGHTING", "COMPETITIVE", "MULTIPLAYER", "ARCADE", "ESPORTS"],
    reviewScore: 8.9,
    totalReviews: 56789,
    developer: "Capcom",
    publisher: "Capcom",
    genre: ["Fighting", "Competitive", "Arcade"],
    releaseDate: "June 2, 2023",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 189
  },
  {
    id: "tekken-8-ps",
    title: "Tekken 8",
    originalPrice: 69.99,
    discountedPrice: 59.99,
    discount: 14,
    platform: "playstation",
    imageUrl: "https://images.pexels.com/photos/159868/mario-yoschi-figures-toys-159868.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/159868/mario-yoschi-figures-toys-159868.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Get ready for the next chapter. Tekken 8 continues the tragic saga of the Mishima bloodline.",
    tags: ["FIGHTING", "COMPETITIVE", "MULTIPLAYER", "3D FIGHTER", "ESPORTS"],
    reviewScore: 8.7,
    totalReviews: 34567,
    developer: "Bandai Namco Studios",
    publisher: "Bandai Namco Entertainment",
    genre: ["Fighting", "Competitive", "3D Fighter"],
    releaseDate: "January 26, 2024",
    activationInstructions: "PlayStation Network account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 145
  },

  // Xbox Games (30 games)
  {
    id: "halo-infinite-xbox",
    title: "Halo Infinite",
    originalPrice: 59.99,
    discountedPrice: 29.99,
    discount: 50,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "When all hope is lost and humanity's fate hangs in the balance, Master Chief is ready to confront the most ruthless foe he's ever faced.",
    tags: ["FPS", "SCI-FI", "MULTIPLAYER", "CAMPAIGN", "XBOX EXCLUSIVE"],
    reviewScore: 8.7,
    totalReviews: 123456,
    developer: "343 Industries",
    publisher: "Microsoft Studios",
    genre: ["FPS", "Sci-Fi", "Action"],
    releaseDate: "December 8, 2021",
    activationInstructions: "Xbox Live account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 234
  },
  {
    id: "forza-horizon-5-xbox",
    title: "Forza Horizon 5",
    originalPrice: 59.99,
    discountedPrice: 29.99,
    discount: 50,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/1298261/pexels-photo-1298261.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1298261/pexels-photo-1298261.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Your Ultimate Horizon Adventure awaits! Explore the vibrant and ever-evolving open world landscapes of Mexico.",
    tags: ["RACING", "OPEN WORLD", "CARS", "MULTIPLAYER", "ARCADE"],
    reviewScore: 9.2,
    totalReviews: 98765,
    developer: "Playground Games",
    publisher: "Microsoft Studios",
    genre: ["Racing", "Open World", "Sports"],
    releaseDate: "November 9, 2021",
    activationInstructions: "Xbox Live account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 189
  },
  {
    id: "gears-5-xbox",
    title: "Gears 5",
    originalPrice: 39.99,
    discountedPrice: 19.99,
    discount: 50,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "From one of gaming's most acclaimed sagas, Gears is bigger than ever, with five thrilling modes and the deepest campaign yet.",
    tags: ["THIRD-PERSON SHOOTER", "CO-OP", "MULTIPLAYER", "SCI-FI", "XBOX EXCLUSIVE"],
    reviewScore: 8.5,
    totalReviews: 67890,
    developer: "The Coalition",
    publisher: "Microsoft Studios",
    genre: ["Third-Person Shooter", "Action", "Sci-Fi"],
    releaseDate: "September 10, 2019",
    activationInstructions: "Xbox Live account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 145
  },
  {
    id: "sea-of-thieves-xbox",
    title: "Sea of Thieves",
    originalPrice: 39.99,
    discountedPrice: 19.99,
    discount: 50,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Sea of Thieves offers the essential pirate experience, from sailing and fighting to exploring and looting.",
    tags: ["PIRATES", "MULTIPLAYER", "ADVENTURE", "CO-OP", "OPEN WORLD"],
    reviewScore: 8.3,
    totalReviews: 89012,
    developer: "Rare",
    publisher: "Microsoft Studios",
    genre: ["Adventure", "Multiplayer", "Pirates"],
    releaseDate: "March 20, 2018",
    activationInstructions: "Xbox Live account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 167
  },
  {
    id: "microsoft-flight-simulator-xbox",
    title: "Microsoft Flight Simulator",
    originalPrice: 59.99,
    discountedPrice: 39.99,
    discount: 33,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/735911/pexels-photo-735911.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/735911/pexels-photo-735911.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "From light planes to wide-body jets, fly highly detailed and accurate aircraft in the next generation of Microsoft Flight Simulator.",
    tags: ["SIMULATION", "FLYING", "REALISTIC", "WORLD", "EDUCATIONAL"],
    reviewScore: 9.0,
    totalReviews: 56789,
    developer: "Asobo Studio",
    publisher: "Microsoft Studios",
    genre: ["Simulation", "Flying", "Educational"],
    releaseDate: "August 18, 2020",
    activationInstructions: "Xbox Live account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 123
  },
  {
    id: "age-of-empires-iv-xbox",
    title: "Age of Empires IV",
    originalPrice: 59.99,
    discountedPrice: 29.99,
    discount: 50,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/279321/pexels-photo-279321.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/279321/pexels-photo-279321.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "One of the most beloved real-time strategy games returns to glory with Age of Empires IV.",
    tags: ["RTS", "STRATEGY", "HISTORICAL", "MULTIPLAYER", "MEDIEVAL"],
    reviewScore: 8.8,
    totalReviews: 45678,
    developer: "Relic Entertainment",
    publisher: "Microsoft Studios",
    genre: ["RTS", "Strategy", "Historical"],
    releaseDate: "October 28, 2021",
    activationInstructions: "Xbox Live account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 134
  },
  {
    id: "ori-will-of-wisps-xbox",
    title: "Ori and the Will of the Wisps",
    originalPrice: 29.99,
    discountedPrice: 14.99,
    discount: 50,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Embark on a new journey in a vast, exotic world where you'll encounter towering enemies and challenging puzzles.",
    tags: ["PLATFORMER", "METROIDVANIA", "BEAUTIFUL", "EMOTIONAL", "INDIE"],
    reviewScore: 9.4,
    totalReviews: 78901,
    developer: "Moon Studios",
    publisher: "Microsoft Studios",
    genre: ["Platformer", "Metroidvania", "Adventure"],
    releaseDate: "March 11, 2020",
    activationInstructions: "Xbox Live account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 156
  },
  {
    id: "state-of-decay-3-xbox",
    title: "State of Decay 3",
    originalPrice: 59.99,
    discountedPrice: 59.99,
    discount: 0,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/1040473/pexels-photo-1040473.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1040473/pexels-photo-1040473.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "The zombie apocalypse survival game you've been waiting for. State of Decay 3 is coming soon.",
    tags: ["ZOMBIES", "SURVIVAL", "OPEN WORLD", "CO-OP", "UPCOMING"],
    reviewScore: 0,
    totalReviews: 0,
    developer: "Undead Labs",
    publisher: "Microsoft Studios",
    genre: ["Survival", "Action", "Zombies"],
    releaseDate: "TBA 2024",
    activationInstructions: "Xbox Live account required.",
    inStock: false,
    deliveryMethod: "Digital Download",
    usersOnPage: 234
  },
  {
    id: "fable-xbox",
    title: "Fable",
    originalPrice: 59.99,
    discountedPrice: 59.99,
    discount: 0,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/1166991/pexels-photo-1166991.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1166991/pexels-photo-1166991.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "A new beginning for the legendary Fable franchise. Explore a land of fantastical creatures and wondrous places.",
    tags: ["RPG", "FANTASY", "OPEN WORLD", "MAGIC", "UPCOMING"],
    reviewScore: 0,
    totalReviews: 0,
    developer: "Playground Games",
    publisher: "Microsoft Studios",
    genre: ["RPG", "Fantasy", "Open World"],
    releaseDate: "TBA 2024",
    activationInstructions: "Xbox Live account required.",
    inStock: false,
    deliveryMethod: "Digital Download",
    usersOnPage: 345
  },
  {
    id: "perfect-dark-xbox",
    title: "Perfect Dark",
    originalPrice: 59.99,
    discountedPrice: 59.99,
    discount: 0,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/1298601/pexels-photo-1298601.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1298601/pexels-photo-1298601.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Agent Joanna Dark returns in this reboot of the classic Perfect Dark franchise.",
    tags: ["FPS", "SCI-FI", "AGENT", "STEALTH", "UPCOMING"],
    reviewScore: 0,
    totalReviews: 0,
    developer: "The Initiative",
    publisher: "Microsoft Studios",
    genre: ["FPS", "Stealth", "Sci-Fi"],
    releaseDate: "TBA 2024",
    activationInstructions: "Xbox Live account required.",
    inStock: false,
    deliveryMethod: "Digital Download",
    usersOnPage: 189
  },
  // Additional Xbox games to reach 30
  {
    id: "psychonauts-2-xbox",
    title: "Psychonauts 2",
    originalPrice: 59.99,
    discountedPrice: 29.99,
    discount: 50,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/159868/mario-yoschi-figures-toys-159868.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/159868/mario-yoschi-figures-toys-159868.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Razputin Aquato, trained acrobat and powerful young psychic, has realized his lifelong dream of joining the international psychic espionage organization.",
    tags: ["PLATFORMER", "PSYCHIC", "ADVENTURE", "UNIQUE", "STORY RICH"],
    reviewScore: 9.1,
    totalReviews: 34567,
    developer: "Double Fine Productions",
    publisher: "Microsoft Studios",
    genre: ["Platformer", "Adventure", "Psychic"],
    releaseDate: "August 25, 2021",
    activationInstructions: "Xbox Live account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 123
  },
  {
    id: "deathloop-xbox",
    title: "Deathloop",
    originalPrice: 59.99,
    discountedPrice: 19.99,
    discount: 67,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "DEATHLOOP transports players to the lawless island of Blackreef in an eternal struggle between two extraordinary assassins.",
    tags: ["TIME LOOP", "FPS", "STEALTH", "UNIQUE", "IMMERSIVE SIM"],
    reviewScore: 8.8,
    totalReviews: 45678,
    developer: "Arkane Studios",
    publisher: "Bethesda Softworks",
    genre: ["FPS", "Stealth", "Time Loop"],
    releaseDate: "September 14, 2021",
    activationInstructions: "Xbox Live account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 167
  },
  {
    id: "hi-fi-rush-xbox",
    title: "Hi-Fi RUSH",
    originalPrice: 29.99,
    discountedPrice: 19.99,
    discount: 33,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&w=1920&h-1080&fit=crop",
    description: "Hi-Fi RUSH is a rhythm action game where everything moves to the beat and the music.",
    tags: ["RHYTHM", "ACTION", "MUSIC", "COLORFUL", "UNIQUE"],
    reviewScore: 9.0,
    totalReviews: 23456,
    developer: "Tango Gameworks",
    publisher: "Bethesda Softworks",
    genre: ["Rhythm", "Action", "Music"],
    releaseDate: "January 25, 2023",
    activationInstructions: "Xbox Live account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 145
  },
  {
    id: "pentiment-xbox",
    title: "Pentiment",
    originalPrice: 19.99,
    discountedPrice: 14.99,
    discount: 25,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/279321/pexels-photo-279321.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/279321/pexels-photo-279321.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "In this historical narrative-driven game, you'll play as Andreas Maler, a master artist working in an abbey.",
    tags: ["NARRATIVE", "HISTORICAL", "MYSTERY", "ART", "MEDIEVAL"],
    reviewScore: 8.6,
    totalReviews: 12345,
    developer: "Obsidian Entertainment",
    publisher: "Microsoft Studios",
    genre: ["Narrative", "Historical", "Mystery"],
    releaseDate: "November 15, 2022",
    activationInstructions: "Xbox Live account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 89
  },
  {
    id: "grounded-xbox",
    title: "Grounded",
    originalPrice: 39.99,
    discountedPrice: 19.99,
    discount: 50,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "The world is a vast, beautiful and dangerous place – especially when you've been shrunk to the size of an ant.",
    tags: ["SURVIVAL", "CO-OP", "CRAFTING", "SHRUNK", "BACKYARD"],
    reviewScore: 8.4,
    totalReviews: 34567,
    developer: "Obsidian Entertainment",
    publisher: "Microsoft Studios",
    genre: ["Survival", "Crafting", "Co-op"],
    releaseDate: "September 27, 2022",
    activationInstructions: "Xbox Live account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 156
  },
  {
    id: "as-dusk-falls-xbox",
    title: "As Dusk Falls",
    originalPrice: 29.99,
    discountedPrice: 14.99,
    discount: 50,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/735911/pexels-photo-735911.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/735911/pexels-photo-735911.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "An interactive drama about two families whose lives become entangled in a robbery-gone-wrong.",
    tags: ["INTERACTIVE DRAMA", "STORY RICH", "CHOICES", "FAMILY", "CRIME"],
    reviewScore: 8.2,
    totalReviews: 15678,
    developer: "Interior Night",
    publisher: "Microsoft Studios",
    genre: ["Interactive Drama", "Story Rich", "Choices"],
    releaseDate: "July 19, 2022",
    activationInstructions: "Xbox Live account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 98
  },
  {
    id: "the-outer-worlds-xbox",
    title: "The Outer Worlds",
    originalPrice: 59.99,
    discountedPrice: 19.99,
    discount: 67,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/1040473/pexels-photo-1040473.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1040473/pexels-photo-1040473.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "The Outer Worlds is a new single-player sci-fi RPG from Obsidian Entertainment and Private Division.",
    tags: ["RPG", "SCI-FI", "SPACE", "CHOICES", "SINGLE PLAYER"],
    reviewScore: 8.5,
    totalReviews: 67890,
    developer: "Obsidian Entertainment",
    publisher: "Private Division",
    genre: ["RPG", "Sci-Fi", "Space"],
    releaseDate: "October 25, 2019",
    activationInstructions: "Xbox Live account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 134
  },
  {
    id: "wasteland-3-xbox",
    title: "Wasteland 3",
    originalPrice: 59.99,
    discountedPrice: 19.99,
    discount: 67,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/1166991/pexels-photo-1166991.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1166991/pexels-photo-1166991.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Following the critically acclaimed 2014 Game of the Year winner Wasteland 2, the RPG series that pioneered the post-apocalyptic genre.",
    tags: ["RPG", "POST-APOCALYPTIC", "TURN-BASED", "TACTICAL", "CO-OP"],
    reviewScore: 8.3,
    totalReviews: 23456,
    developer: "inXile Entertainment",
    publisher: "inXile Entertainment",
    genre: ["RPG", "Turn-Based", "Post-Apocalyptic"],
    releaseDate: "August 28, 2020",
    activationInstructions: "Xbox Live account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 112
  },
  {
    id: "crusader-kings-iii-xbox",
    title: "Crusader Kings III",
    originalPrice: 49.99,
    discountedPrice: 24.99,
    discount: 50,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/1298601/pexels-photo-1298601.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1298601/pexels-photo-1298601.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Love, fight, scheme, and claim greatness. Determine your noble house's legacy in the sprawling grand strategy of Crusader Kings III.",
    tags: ["GRAND STRATEGY", "MEDIEVAL", "DYNASTY", "COMPLEX", "HISTORICAL"],
    reviewScore: 9.1,
    totalReviews: 45678,
    developer: "Paradox Development Studio",
    publisher: "Paradox Interactive",
    genre: ["Grand Strategy", "Medieval", "Historical"],
    releaseDate: "September 1, 2020",
    activationInstructions: "Xbox Live account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 167
  },
  {
    id: "cities-skylines-xbox",
    title: "Cities: Skylines",
    originalPrice: 29.99,
    discountedPrice: 7.49,
    discount: 75,
    platform: "xbox",
    imageUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Cities: Skylines is a modern take on the classic city simulation.",
    tags: ["CITY BUILDER", "SIMULATION", "MANAGEMENT", "CREATIVE", "RELAXING"],
    reviewScore: 8.7,
    totalReviews: 89012,
    developer: "Colossal Order",
    publisher: "Paradox Interactive",
    genre: ["City Builder", "Simulation", "Management"],
    releaseDate: "March 10, 2015",
    activationInstructions: "Xbox Live account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 145
  },

  // Nintendo Games (30 games)
  {
    id: "super-mario-odyssey-nintendo",
    title: "Super Mario Odyssey",
    originalPrice: 59.99,
    discountedPrice: 39.99,
    discount: 33,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Join Mario on a massive, globe-trotting 3D adventure and use his incredible new abilities to collect Moons.",
    tags: ["PLATFORMER", "ADVENTURE", "FAMILY FRIENDLY", "3D", "NINTENDO EXCLUSIVE"],
    reviewScore: 9.7,
    totalReviews: 234567,
    developer: "Nintendo EPD",
    publisher: "Nintendo",
    genre: ["Platformer", "Adventure", "3D"],
    releaseDate: "October 27, 2017",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 345
  },
  {
    id: "zelda-breath-of-wild-nintendo",
    title: "The Legend of Zelda: Breath of the Wild",
    originalPrice: 59.99,
    discountedPrice: 39.99,
    discount: 33,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/1298601/pexels-photo-1298601.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1298601/pexels-photo-1298601.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Step into a world of discovery, exploration, and adventure in The Legend of Zelda: Breath of the Wild.",
    tags: ["OPEN WORLD", "ADVENTURE", "EXPLORATION", "PUZZLE", "NINTENDO EXCLUSIVE"],
    reviewScore: 9.7,
    totalReviews: 345678,
    developer: "Nintendo EPD",
    publisher: "Nintendo",
    genre: ["Adventure", "Open World", "Action"],
    releaseDate: "March 3, 2017",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 456
  },
  {
    id: "zelda-tears-kingdom-nintendo",
    title: "The Legend of Zelda: Tears of the Kingdom",
    originalPrice: 69.99,
    discountedPrice: 59.99,
    discount: 14,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/1166991/pexels-photo-1166991.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1166991/pexels-photo-1166991.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "An epic adventure across the land and skies of Hyrule awaits in The Legend of Zelda: Tears of the Kingdom.",
    tags: ["OPEN WORLD", "ADVENTURE", "BUILDING", "EXPLORATION", "NINTENDO EXCLUSIVE"],
    reviewScore: 9.6,
    totalReviews: 189012,
    developer: "Nintendo EPD",
    publisher: "Nintendo",
    genre: ["Adventure", "Open World", "Action"],
    releaseDate: "May 12, 2023",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 567
  },
  {
    id: "super-smash-bros-ultimate-nintendo",
    title: "Super Smash Bros. Ultimate",
    originalPrice: 59.99,
    discountedPrice: 39.99,
    discount: 33,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/159868/mario-yoschi-figures-toys-159868.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/159868/mario-yoschi-figures-toys-159868.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "The biggest crossover in gaming history. Fighters from every corner of the gaming world clash in the ultimate showdown.",
    tags: ["FIGHTING", "MULTIPLAYER", "PARTY", "COMPETITIVE", "NINTENDO EXCLUSIVE"],
    reviewScore: 9.3,
    totalReviews: 278901,
    developer: "Bandai Namco Studios",
    publisher: "Nintendo",
    genre: ["Fighting", "Multiplayer", "Party"],
    releaseDate: "December 7, 2018",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 389
  },
  {
    id: "mario-kart-8-deluxe-nintendo",
    title: "Mario Kart 8 Deluxe",
    originalPrice: 59.99,
    discountedPrice: 39.99,
    discount: 33,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Hit the road with the definitive version of Mario Kart 8 and play anytime, anywhere!",
    tags: ["RACING", "MULTIPLAYER", "PARTY", "FAMILY FRIENDLY", "NINTENDO EXCLUSIVE"],
    reviewScore: 9.3,
    totalReviews: 456789,
    developer: "Nintendo EPD",
    publisher: "Nintendo",
    genre: ["Racing", "Multiplayer", "Party"],
    releaseDate: "April 28, 2017",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 234
  },
  {
    id: "animal-crossing-new-horizons-nintendo",
    title: "Animal Crossing: New Horizons",
    originalPrice: 59.99,
    discountedPrice: 39.99,
    discount: 33,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Escape to a deserted island and create your own paradise as you explore, create, and customize in Animal Crossing: New Horizons.",
    tags: ["LIFE SIMULATION", "RELAXING", "CREATIVE", "SOCIAL", "NINTENDO EXCLUSIVE"],
    reviewScore: 9.0,
    totalReviews: 345678,
    developer: "Nintendo EPD",
    publisher: "Nintendo",
    genre: ["Life Simulation", "Creative", "Social"],
    releaseDate: "March 20, 2020",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 278
  },
  {
    id: "splatoon-3-nintendo",
    title: "Splatoon 3",
    originalPrice: 59.99,
    discountedPrice: 49.99,
    discount: 17,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Enter the Splatlands, a sun-scorched desert inhabited by battle-hardened Inklings and Octolings.",
    tags: ["THIRD-PERSON SHOOTER", "MULTIPLAYER", "COLORFUL", "UNIQUE", "NINTENDO EXCLUSIVE"],
    reviewScore: 8.9,
    totalReviews: 123456,
    developer: "Nintendo EPD",
    publisher: "Nintendo",
    genre: ["Third-Person Shooter", "Multiplayer", "Action"],
    releaseDate: "September 9, 2022",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 189
  },
  {
    id: "pokemon-scarlet-violet-nintendo",
    title: "Pokémon Scarlet and Violet",
    originalPrice: 59.99,
    discountedPrice: 49.99,
    discount: 17,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/1040473/pexels-photo-1040473.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1040473/pexels-photo-1040473.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Catch, battle, and train Pokémon in the Paldea Region, a vast land filled with lakes, towering peaks, wastelands, small towns, and sprawling cities.",
    tags: ["RPG", "POKEMON", "OPEN WORLD", "ADVENTURE", "NINTENDO EXCLUSIVE"],
    reviewScore: 7.8,
    totalReviews: 234567,
    developer: "Game Freak",
    publisher: "Nintendo",
    genre: ["RPG", "Adventure", "Pokemon"],
    releaseDate: "November 18, 2022",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 345
  },
  {
    id: "metroid-dread-nintendo",
    title: "Metroid Dread",
    originalPrice: 59.99,
    discountedPrice: 39.99,
    discount: 33,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/735911/pexels-photo-735911.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/735911/pexels-photo-735911.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Join bounty hunter Samus Aran as she tries to escape a deadly alien world plagued by a mechanical menace.",
    tags: ["METROIDVANIA", "ACTION", "SCI-FI", "EXPLORATION", "NINTENDO EXCLUSIVE"],
    reviewScore: 9.1,
    totalReviews: 89012,
    developer: "MercurySteam",
    publisher: "Nintendo",
    genre: ["Metroidvania", "Action", "Sci-Fi"],
    releaseDate: "October 8, 2021",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 156
  },
  {
    id: "xenoblade-chronicles-3-nintendo",
    title: "Xenoblade Chronicles 3",
    originalPrice: 59.99,
    discountedPrice: 39.99,
    discount: 33,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/279321/pexels-photo-279321.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/279321/pexels-photo-279321.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Join Noah and Mio, members of the two opposing nations of Keves and Agnus, on a heartfelt journey to end the cycle of violence.",
    tags: ["JRPG", "STORY RICH", "ANIME", "OPEN WORLD", "NINTENDO EXCLUSIVE"],
    reviewScore: 8.9,
    totalReviews: 67890,
    developer: "Monolith Soft",
    publisher: "Nintendo",
    genre: ["JRPG", "Adventure", "Anime"],
    releaseDate: "July 29, 2022",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 134
  },
  // Additional Nintendo games to reach 30
  {
    id: "fire-emblem-engage-nintendo",
    title: "Fire Emblem Engage",
    originalPrice: 59.99,
    discountedPrice: 49.99,
    discount: 17,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "In a war against the Fell Dragon, four kingdoms worked together with heroes from other worlds to seal away this great evil.",
    tags: ["TACTICAL RPG", "STRATEGY", "ANIME", "TURN-BASED", "NINTENDO EXCLUSIVE"],
    reviewScore: 8.4,
    totalReviews: 45678,
    developer: "Intelligent Systems",
    publisher: "Nintendo",
    genre: ["Tactical RPG", "Strategy", "Turn-Based"],
    releaseDate: "January 20, 2023",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 123
  },
  {
    id: "kirby-forgotten-land-nintendo",
    title: "Kirby and the Forgotten Land",
    originalPrice: 59.99,
    discountedPrice: 39.99,
    discount: 33,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Join Kirby in an unforgettable journey through a mysterious world in a delightful 3D platforming adventure.",
    tags: ["PLATFORMER", "3D", "FAMILY FRIENDLY", "ADVENTURE", "NINTENDO EXCLUSIVE"],
    reviewScore: 8.8,
    totalReviews: 78901,
    developer: "HAL Laboratory",
    publisher: "Nintendo",
    genre: ["Platformer", "Adventure", "3D"],
    releaseDate: "March 25, 2022",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 167
  },
  {
    id: "mario-wonder-nintendo",
    title: "Super Mario Bros. Wonder",
    originalPrice: 59.99,
    discountedPrice: 54.99,
    discount: 8,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/163036/mario-luigi-yoschi-figures-163036.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Mario's latest side-scrolling adventure hands you a Wonder Flower that changes the rules.",
    tags: ["PLATFORMER", "2D", "FAMILY FRIENDLY", "WONDER", "NINTENDO EXCLUSIVE"],
    reviewScore: 9.2,
    totalReviews: 123456,
    developer: "Nintendo EPD",
    publisher: "Nintendo",
    genre: ["Platformer", "2D", "Adventure"],
    releaseDate: "October 20, 2023",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 234
  },
  {
    id: "pikmin-4-nintendo",
    title: "Pikmin 4",
    originalPrice: 59.99,
    discountedPrice: 49.99,
    discount: 17,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/1166991/pexels-photo-1166991.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1166991/pexels-photo-1166991.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Meet even more Pikmin (and Oatchi) on a planet full of wonder! These tiny, plant-like creatures are incredibly helpful.",
    tags: ["STRATEGY", "PUZZLE", "CUTE", "EXPLORATION", "NINTENDO EXCLUSIVE"],
    reviewScore: 8.7,
    totalReviews: 56789,
    developer: "Nintendo EPD",
    publisher: "Nintendo",
    genre: ["Strategy", "Puzzle", "Adventure"],
    releaseDate: "July 21, 2023",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 145
  },
  {
    id: "bayonetta-3-nintendo",
    title: "Bayonetta 3",
    originalPrice: 59.99,
    discountedPrice: 29.99,
    discount: 50,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/1298601/pexels-photo-1298601.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1298601/pexels-photo-1298601.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "The witch. The legend. The one and only Bayonetta. Experience the climactic conclusion to the Bayonetta origins trilogy.",
    tags: ["ACTION", "HACK AND SLASH", "STYLISH", "MATURE", "NINTENDO EXCLUSIVE"],
    reviewScore: 8.5,
    totalReviews: 34567,
    developer: "PlatinumGames",
    publisher: "Nintendo",
    genre: ["Action", "Hack and Slash", "Stylish"],
    releaseDate: "October 28, 2022",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 123
  },
  {
    id: "mario-party-superstars-nintendo",
    title: "Mario Party Superstars",
    originalPrice: 59.99,
    discountedPrice: 39.99,
    discount: 33,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/159868/mario-yoschi-figures-toys-159868.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/159868/mario-yoschi-figures-toys-159868.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "The Mario Party series is back with 5 classic boards from the Nintendo 64 Mario Party games.",
    tags: ["PARTY", "MULTIPLAYER", "BOARD GAME", "FAMILY FRIENDLY", "NINTENDO EXCLUSIVE"],
    reviewScore: 8.3,
    totalReviews: 89012,
    developer: "NDcube",
    publisher: "Nintendo",
    genre: ["Party", "Multiplayer", "Board Game"],
    releaseDate: "October 29, 2021",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 178
  },
  {
    id: "paper-mario-origami-king-nintendo",
    title: "Paper Mario: The Origami King",
    originalPrice: 59.99,
    discountedPrice: 39.99,
    discount: 33,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "The kingdom has been ravaged by an origami menace! Join Mario and his new partner, Olivia, as they battle evil Folded Soldiers.",
    tags: ["RPG", "PAPER", "ADVENTURE", "PUZZLE", "NINTENDO EXCLUSIVE"],
    reviewScore: 8.0,
    totalReviews: 67890,
    developer: "Intelligent Systems",
    publisher: "Nintendo",
    genre: ["RPG", "Adventure", "Puzzle"],
    releaseDate: "July 17, 2020",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 134
  },
  {
    id: "donkey-kong-tropical-freeze-nintendo",
    title: "Donkey Kong Country: Tropical Freeze",
    originalPrice: 59.99,
    discountedPrice: 39.99,
    discount: 33,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Swing into action with the biggest Donkey Kong adventure yet! Traverse islands packed with platforming perfection.",
    tags: ["PLATFORMER", "2D", "CHALLENGING", "FAMILY FRIENDLY", "NINTENDO EXCLUSIVE"],
    reviewScore: 8.9,
    totalReviews: 78901,
    developer: "Retro Studios",
    publisher: "Nintendo",
    genre: ["Platformer", "2D", "Adventure"],
    releaseDate: "May 4, 2018",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 156
  },
  {
    id: "luigis-mansion-3-nintendo",
    title: "Luigi's Mansion 3",
    originalPrice: 59.99,
    discountedPrice: 39.99,
    discount: 33,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Luigi's invited to the towering Last Resort hotel, but when Mario and friends go missing, our green-clad hero will have to conquer his fears.",
    tags: ["ADVENTURE", "GHOST", "PUZZLE", "FAMILY FRIENDLY", "NINTENDO EXCLUSIVE"],
    reviewScore: 8.6,
    totalReviews: 123456,
    developer: "Next Level Games",
    publisher: "Nintendo",
    genre: ["Adventure", "Puzzle", "Ghost"],
    releaseDate: "October 31, 2019",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 189
  },
  {
    id: "arms-nintendo",
    title: "ARMS",
    originalPrice: 59.99,
    discountedPrice: 29.99,
    discount: 50,
    platform: "nintendo",
    imageUrl: "https://images.pexels.com/photos/1040473/pexels-photo-1040473.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&fit=crop",
    heroImageUrl: "https://images.pexels.com/photos/1040473/pexels-photo-1040473.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop",
    description: "Grab the Joy-Con controllers and throw punches using extendable arms! Choose a fighting champion from around the world.",
    tags: ["FIGHTING", "MOTION CONTROLS", "MULTIPLAYER", "UNIQUE", "NINTENDO EXCLUSIVE"],
    reviewScore: 7.8,
    totalReviews: 45678,
    developer: "Nintendo EPD",
    publisher: "Nintendo",
    genre: ["Fighting", "Motion Controls", "Multiplayer"],
    releaseDate: "June 16, 2017",
    activationInstructions: "Nintendo Account required.",
    inStock: true,
    deliveryMethod: "Digital Download",
    usersOnPage: 98
  }
];

export const useGameStore = create<GameStore>((set, get) => ({
  games: gameData,
  getGameById: (id: string) => {
    const { games } = get();
    return games.find(game => game.id === id);
  },
  getGamesByPlatform: (platform: string) => {
    const { games } = get();
    return games.filter(game => game.platform.toLowerCase() === platform.toLowerCase());
  },
  searchGames: (query: string, platform?: string) => {
    const { games } = get();
    return games.filter(game => {
      const matchesQuery = game.title.toLowerCase().includes(query.toLowerCase());
      const matchesPlatform = !platform || game.platform.toLowerCase() === platform.toLowerCase();
      return matchesQuery && matchesPlatform;
    });
  }
}));